[phases]
setup = [
    "python3",
    "gcc",
    "curl",
    "tar"
]

[phases.install]
commands = [
    "python -m venv --copies /opt/venv",
    ". /opt/venv/bin/activate && pip install -r requirements.txt"
]

[start]
command = "./startup.sh"